### ISSUE TITLE
Draw a diagram explaining the process with upload token

### ISSUE THREAD

**Issue by tvierro2** [Freshmen/freshman-orienteering#18]
We need to figure out how to handle the file uploads when only the organizer is logged in to CAN

**Comment by Vidhuran** [comment]
The FSIO doesn't really care if the user is logged in before making an upload using the upload token. So, this makes it possible to just pass on the upload token to anybody and they can make an upload using the upload token they had received. But the drawback is the upload has to be done using the REST API and not via the CAN js SDK.
