### ISSUE TITLE
Calculate distance between current position and checkpoint

### ISSUE THREAD

**Issue by xiangts** [Freshmen/freshman-orienteering#48]

**Comment by Kenzku** [comment]
line 50    Geolocation.initialize(watchPositionSuccess, getCurrentPositionSuccess);
line 51    Geolocation.watchPosition(); in nokiaMaps.js
with the javascript file geolocation.js, these three things overwritten the HTML 5 object Geolocation in navigator.geolocation which also returns a Geolocation object. 

This will cause all later functions cannot use navigator.geolocation to get current location. One issue from the overwritten is the getCurrentPosition(), which does not support callback from xiangts' code. 

Try changing the name to other than Geolocation.
